version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: wtech_db
    ports:
      - "3306:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: a
      POSTGRES_DB: laravel
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
